# Fake News Detection
在此整理了相关的文献，主要是与假新闻检测领域相关的，希望大家多多指正。
## Survey
* Combating Misinformation in the Age of LLMs: Opportunities and Challenges (**AI Magazine 2024**) [[paper](https://arxiv.org/abs/2311.05656)]
* Combating Online Misinformation Videos: Characterization, Detection, and Future Directions (**MM 2023**) [[paper](https://dl.acm.org/doi/abs/10.1145/3581783.3612426)]
* A survey on fake news and rumour detection techniques (**Information Sciences 2019**) [[paper](https://dl.acm.org/doi/abs/10.1145/3581783.3612426)]
## 使用（多模态）大型语言模型（即 （M）LLM）的假新闻检测框架
### 2025
* The Truth Becomes Clearer Through Debate! Multi-Agent Systems with Large Language Models Unmask Fake News (**SIGIR**) [[paper](https://dl.acm.org/doi/abs/10.1145/3726302.3730092)]
* BiDeV: Bilateral Defusing Verification for Complex Claim Fact-Checking (**Arxiv**) [[paper](https://arxiv.org/pdf/2202.07082.pdf)]
### 2024
* SNIFFER: Multimodal Large Language Model for Explainable Out-of-Context Misinformation Detection (**CVPR**) [[paper](https://openaccess.thecvf.com/content/CVPR2024/papers/Qi_SNIFFER_Multimodal_Large_Language_Model_for_Explainable_Out-of-Context_Misinformation_Detection_CVPR_2024_paper.pdf)][[code](https://github.com/MischaQI/Sniffer)]
* Bad Actor, Good Advisor: Exploring the Role of Large Language Models in Fake News Detection (**AAAI**) [[paper](https://ojs.aaai.org/index.php/AAAI/article/view/30214)][[code](https://github.com/ictmcg/arg)]  
* TELLER: A Trustworthy Framework for Explainable, Generalizable and Controllable Fake News Detection (**ACL Findings**) [[paper](https://arxiv.org/abs/2402.07776)][[code](https://github.com/less-and-less-bugs/Trust_TELLER)]  
* DELL: Generating Reactions and Explanations for LLM-Based Misinformation Detection (**ACL Findings**) [[paper](https://arxiv.org/abs/2402.10426)][[code](https://github.com/whr000001/DELL)]  
* Explainable Fake News Detection with Large Language Model via Defense Among Competing Wisdom (**WWW**) [[paper](https://dl.acm.org/doi/abs/10.1145/3589334.3645471)][[code](https://github.com/wangbo9719/L-Defense_EFND)]  
* Message Injection Attack on Rumor Detection under the Black-Box Evasion Setting Using Large Language Model (**WWW**) [[paper](https://dl.acm.org/doi/10.1145/3589334.3648139)]
* Towards Robust Evidence-Aware Fake News Detection via Improving Semantic Perception (**COLING**) [[paper](https://aclanthology.org/2024.lrec-main.1443/)]
* Let Silence Speak: Enhancing Fake News Detection with Generated Comments from Large Language Models (**CIKM**) [[paper](https://arxiv.org/abs/2405.16631)]
* Re-Search for The Truth: Multi-round Retrieval-augmented Large Language Models are Strong Fake News Detectors (**Arxiv**) [[paper](https://arxiv.org/abs/2403.09747)]
* Large Language Model Agent for Fake News Detection (**Arxiv**) [[paper](https://arxiv.org/html/2405.01593v1)]
### 2023
* Faking Fake News for Real Fake News Detection: Propaganda-Loaded Training Data Generation (**ACL**) [[paper](https://aclanthology.org/2023.acl-long.815/)] 
* Fighting Fire with Fire: The Dual Role of LLMs in Crafting and Detecting Elusive Disinformation (**EMNLP**) [[paper](https://aclanthology.org/2023.emnlp-main.883/)]
* Explainable Claim Verification via Knowledge-Grounded Reasoning with Large Language Models (**EMNLP Findings**) [[paper](https://aclanthology.org/2023.findings-emnlp.416/)]
* Clean-label Poisoning Attack against Fake News Detection Models (**BigData**) [[paper](https://ieeexplore.ieee.org/document/10386777)]
## LLMs在假新闻领域其他任务上的应用
## 2024
* From Skepticism to Acceptance: Simulating the Attitude Dynamics Toward Fake News (**IJCAI**) [[paper](https://arxiv.org/abs/2403.09498))]
* Fake News in Sheep's Clothing: Robust Fake News Detection Against LLM-Empowered Style Attacks (**KDD**) [[paper](https://dl.acm.org/doi/10.1145/3637528.3671977))]
* Preventing and Detecting Misinformation Generated by Large Language Models (**SIGIR**) [[paper](https://dl.acm.org/doi/10.1145/3626772.3661377))]
* Large-Language-Model-Powered Agent-Based Framework for Misinformation and Disinformation Research: Opportunities and Open Challenges (**IEEE S&P**) [[paper](https://arxiv.org/abs/2310.07545))]
* From a Tiny Slip to a Giant Leap: An LLM-Based Simulation for Fake News Evolution (**Arxiv**) [[paper](https://arxiv.org/html/2410.19064v1))]
## 假新闻视频检测
### 2025
* T$^3$SVFND: Towards an Evolving Fake News Detector for Emergencies with Test-time Training on Short Video Platforms (**DASFAA**) [[paper](https://arxiv.org/pdf/2507.20286)][[code](https://github.com/ZhangLiyuan11/TTTSVFND)]
* IMOL: Incomplete-Modality-Tolerant Learning for Multi-Domain Fake News Video Detection (**ACL**) [[paper](https://aclanthology.org/2025.acl-long.1494/)][[code](https://github.com/zzeng1998/IMOL_misinformation)]
* Text-Guided Fine-grained Counterfactual Inference for Short Video Fake News Detection (**AAAI**) [[paper](https://aclanthology.org/2025.acl-long.1494/)]
* Multi-modal Similarity Guided Adaptive Fusion Network for Short Video Fake News Detection (**ICMR**) [[paper](https://dl.acm.org/doi/10.1145/3731715.3733400)][[code](https://github.com/pp-jia/MSAF-Net)]
* MFSVFND: Multimodal Fusion Network for Detecting Fake News on Short Video Platforms (**ICMR**) [[paper](https://dl.acm.org/doi/10.1145/3731715.3733486)][[code](https://github.com/ZhangLiyuan11/MFSVFND-main)]
* Following Clues, Approaching the Truth: Explainable Micro-Video Rumor Detection via Chain-of-Thought Reasoning (**WWW**) [[paper](https://openreview.net/pdf?id=lq2jDWv3w0)][[code](https://github.com/ICDM-UESTC/ExMRD)]
* Enhancing Fake News Video Detection via LLM-Driven Creative Process Simulation (**CIKM**) [[paper](https://arxiv.org/abs/2510.04024)][[code](https://github.com/ICTMCG/AgentAug)]
* Multimodal Fake News Video Explanation Generation (**Arxiv**) [[paper](https://openreview.net/pdf?id=lq2jDWv3w0)]
### 2024
* FakingRecipe: Detecting Fake News on Short Video Platforms from the Perspective of Creative Process (**MM**) [[paper](https://dl.acm.org/doi/10.1145/3664647.3680663)][[code](https://github.com/ICTMCG/FakingRecipe)]
* Mitigating World Biases: A Multimodal Multi-View Debiasing Framework for Fake News Video Detection (**MM**) [[paper](https://dl.acm.org/doi/10.1145/3664647.3681673)]
* Unveiling Opinion Evolution via Prompting and Diffusion for Short Video Fake News Detection (**ACL**) [[paper](https://aclanthology.org/2024.findings-acl.642.pdf)]
* Interpretable Short Video Rumor Detection based on Modality Tampering (**COLING**) [[paper](https://aclanthology.org/2024.lrec-main.804.pdf)]
* Official-NV: A News Video Dataset for Multimodal Fake News Detection (**Arxiv**) [[paper](https://arxiv.org/pdf/2407.19493)]
### 2023
* FakeSV: A Multimodal Benchmark with Rich Social Context for Fake News Detection on Short Video Platforms (**AAAI**) [[paper](https://arxiv.org/pdf/2211.10973)][[code](https://github.com/ICTMCG/FakeSV)]
* Improving Fake News Video Detection by Correlating with Neighbors (**ACL**) [[paper](https://arxiv.org/pdf/2306.05241)][[code](https://github.com/ICTMCG/NEED)]
* Multimodal Short Video Rumor Detection System Based on Contrastive Learning (**Arxiv**) [[paper](https://arxiv.org/pdf/2304.08401)]
### 2022及更早期工作
* A Multimodal Misinformation Detector for COVID-19 Short Videos on TikTok (**IEEE BigData 2021**) [[paper](https://ieeexplore.ieee.org/document/9671928)]
* Using Adversarial Learning and Biterm Topic Model for an Effective Fake News Video Detection System on Heterogeneous Topics and Short Texts (**IEEE Access 2021**) [[paper](https://ieeexplore.ieee.org/document/9585513)]
* NLP-based Feature Extraction for the Detection of COVID-19 Misinformation Videos on YouTube (**AVL 2020 Workshop**) [[paper](https://www.sciencedirect.com/org/science/article/abs/pii/S1468452718000409)]
* Towards Automatic Detection of Misinformation in Online Medical Videos (**ICMI 2019**) [[paper](https://dl.acm.org/doi/10.1145/3340555.3353763)]
* A corpus of debunked and verified user-generated videos (**Online Information Review 2018**) [[paper](https://www.sciencedirect.com/org/science/article/abs/pii/S1468452718000409)]
## 多模态假新闻检测（文本-图像）
### 2025
* Graph with Sequence: Broad-Range Semantic Modeling for Fake News Detection (**WWW**) [[paper](https://arxiv.org/pdf/2412.05672v2)]
* Multimodal Taylor Series Network For Misinformation Detection (**WWW**) [[paper](https://openreview.net/pdf?id=Ay5XucNRSR)][[code](https://github.com/OneForAllSama/MTS)]
* Modality Interactive Mixture-of-Experts for Fake News Detection (**WWW**) [[paper](https://openreview.net/pdf?id=Ay5XucNRSR)][[code](https://github.com/yliuaa/MIMoE-FND)]
### 2024
* MMDFND: Multi-modal Multi-Domain Fake News Detection (**MM**) [[paper](https://dl.acm.org/doi/10.1145/3664647.3681317)][[code](https://github.com/yutchina/MMDFND)]
* Harmfully Manipulated Images Matter in Multimodal Misinformation Detection (**MM**) [[paper](https://dl.acm.org/doi/10.1145/3664647.3681322)][[code](https://github.com/wangbing1416/HAMI-M3D)]
* Fake News Detection via Multi-scale Semantic Alignment and Cross-modal Attention (**SIGIR**) [[paper](https://dl.acm.org/doi/abs/10.1145/3626772.3657905)][[code](https://github.com/kingdommm/MSACA_pytorch)]
* Multi-Task Network Guided Multimodal Fusion for Fake News Detection (**ACML**) [[paper](https://proceedings.mlr.press/v260/ma25a.html)]
### 2023
* Bootstrapping Multi-View Representations for Fake News Detection (**AAAI**) [[paper](https://github.com/yingqichao/fnd-bootstrap)][[code](https://github.com/yingqichao/fnd-bootstrap)]
* See How You Read? Multi-Reading Habits Fusion Reasoning for Multi-Modal Fake News Detection (**AAAI**) [[paper](https://ojs.aaai.org/index.php/AAAI/article/view/26609)]
* Cross-modal Contrastive Learning for Multimodal Fake News Detection (**MM**) [[paper](https://arxiv.org/abs/2302.14057)][[code](https://github.com/wishever/COOLANT)]
* Enhancing Fake News Detection in Social Media via Label Propagation on Cross-modal Tweet Graph (**MM**) [[paper](https://arxiv.org/abs/2406.09884)][[code](https://github.com/zhaowanqing/FCN-LP)]
* Hierarchical Semantic Enhancement Network for Multimodal Fake News Detection (**MM**) [[paper](https://dl.acm.org/doi/10.1145/3581783.3612423)][[code](https://github.com/wangjinguang502/HMCAN)]
* A Generalized Deep Markov Random Fields Framework for Fake News Detection (**IJCAI**) [[paper](https://www.ijcai.org/proceedings/2023/0529.pdf)][[code](https://github.com/jindi-tju/ALGM)]
* A Generalized Deep Markov Random Fields Framework for Fake News Detection (**IJCAI**) [[paper](https://www.ijcai.org/proceedings/2023/0529.pdf)][[code](https://github.com/jindi-tju/ALGM)]
* MR$^2$: A Benchmark for Multimodal Retrieval-Augmented Rumor Detection in Social Media (**SIGIR**) [[paper](https://dl.acm.org/doi/10.1145/3539618.3591896)][[code](https://github.com/THU-BPM/MR2)]
* Causal Intervention and Counterfactual Reasoning for Multi-modal Fake News Detection (**ACL**) [[paper](https://aclanthology.org/2023.acl-long.37.pdf)] 
* Multimodal Fake News Detection via CLIP-Guided Learning (**ICME**) [[paper](https://ieeexplore.ieee.org/abstract/document/10219997)][[code](https://github.com/zhouyangming/FND-CLIP-Fake-News-Detection)]
* Multi-modal Fake News Detection on Social Media via Multi-grained Information Fusion (**ICMR**) [[paper](https://arxiv.org/abs/2304.00827)]
### 2022及更早期工作
* Cross-modal Ambiguity Learning for Multimodal Fake News Detection (**WWW 2022**) [[paper](https://web.archive.org/web/20220428130656id_/https://dl.acm.org/doi/pdf/10.1145/3485447.3511968)][[code](https://github.com/cyxanna/CAFE)]
* Multimodal Emergent Fake News Detection via Meta Neural Process Networks (**KDD 2021**) [[paper](https://arxiv.org/pdf/2106.13711)]
* Multimodal Fusion with Co-Attention Networks for Fake News Detection (**ACL 2021**) [[paper](https://aclanthology.org/2021.findings-acl.226.pdf)][[code](https://github.com/wuyang45/MCAN_code)]
* Detecting Cross-Modal Inconsistency to Defend Against Neural Fake News (**EMNLP 2020**) [[paper](https://aclanthology.org/2020.emnlp-main.163.pdf)]
* Exploiting Multi-domain Visual Information for Fake News Detection (**ICDM 2020**) [[paper](https://ieeexplore.ieee.org/abstract/document/8970940)]
* SAFE: Similarity-Aware Multi-Modal Fake News Detection (**PAKDD 2020**) [[paper](https://link.springer.com/chapter/10.1007/978-3-030-47436-2_27)]
* MVAE: Multimodal Variational Autoencoder for Fake News Detection (**WWW 2019**) [[paper](https://dl.acm.org/doi/abs/10.1145/3308558.3313552?casa_token=tzDWRQ_VVxEAAAAA:Fc3ubDseJsk05pUdznqtA4cDD9BGemHHh8A1T6Nzur8qa0SU8SQY8O7_KRoj8tE_Ah75p8sslKjo4bU)]
* Rumor Detection with Hierarchical Social Attention Network (**CIKM 2018**) [[paper](https://dl.acm.org/doi/abs/10.1145/3269206.3271709?casa_token=5ODcLmf4aHkAAAAA:vyQxpSmSkaNDQbzuqUL81HeLeKncNpLa8wEOxANLqGzRXU4W1SZ05Wwgo7BZgegvtW_v5KMt0-UHcmI)]
* EANN: Event Adversarial Neural Networks for Multi-Modal Fake News Detection (**KDD 2018**) [[paper](https://dl.acm.org/doi/abs/10.1145/3219819.3219903?casa_token=_1c4Ao5K0moAAAAA:jUDfxV9HoKVeRQnGwXYI6oGEm1MMOusLGjPiZjEAOm94MVld0ntG44G4kwdK_qLtipJa32ngFQE995U)]
* Multimodal Fusion with Recurrent Neural Networks for Rumor Detection on Microblogs (**MM 2017**) [[paper](https://dl.acm.org/doi/abs/10.1145/3123266.3123454?casa_token=YezZ9B--TsAAAAAA:-tXSt-GU3owhdAj1Oaa5PEqwCdO0kfIXfL_VDQJavItIcAswt_rAyxBDucIJxEAXxj5pdbMTT5lYH7Q)]
## 单峰假新闻检测
### 仅文本
* Meta-prompt based learning for low-resource false information detection (**Information Processing & Management 2023**) [[paper](https://www.sciencedirect.com/science/article/abs/pii/S030645732300016X)]
* Fake news detection via knowledgeable prompt learning (**Information Processing & Management 2022**) [[paper](https://www.sciencedirect.com/science/article/abs/pii/S030645732200139X)]
* Explainable Tsetlin Machine Framework for Fake News Detection with Credibility Score Assessment (**LREC 2022**) [[paper](https://aclanthology.org/2022.lrec-1.523/)]
* Capturing the Style of Fake News (**AAAI 2020**) [[paper](https://aaai.org/papers/00490-capturing-the-style-of-fake-news/)]
* Learning Hierarchical Discourse-level Structure for Fake News Detection (**NAACL 2019**) [[paper](https://aclanthology.org/N19-1347/)]
* Neural User Response Generator: Fake News Detection with Collective User Intelligence (**IJCAI 2018**) [[paper](https://www.ijcai.org/Proceedings/2018/0533.pdf)]
### 仅视觉
* Exploiting multi-domain visual information for fake news detection (**ICDM 2019**) [[paper](https://ieeexplore.ieee.org/document/8970940))]
* Transformer-Based Image Inpainting Detection via Label Decoupling and Constrained Adversarial Training (**TCSVT 2023**) [[paper](https://ieeexplore.ieee.org/document/10196329))]
* Unsupervised Generative Fake Image Detector (**TCSVT 2024**) [[paper](https://ieeexplore.ieee.org/document/10487975))]
